version: '3'

services:
  nats:
    image: nats:2.7.2
    command: '-c nats-server.conf'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
      - 9222:9222
    restart: always
    volumes:
      - ./nats-server.conf:/nats-server.conf
      - ./conf:/conf
    depends_on:
      - nats-account
  nats-account:
    image: synadia/nats-account-server:1.0.0
    command: '-c nats-account-server.conf'
    volumes:
      - ./nats-account-server.conf:/nats-account-server.conf
      - ./conf:/conf
      - ./tmp:/tmp/as_store
    restart: always
    ports:
      - 9090:9090
  nats-migrations:
    image: ${DOCKER_REGISTRY}/teta-nats-migrate:${APP_VERSION}
    environment:
      - DOTNET_ENVIRONMENT=Compose
    restart: on-failure:5
    depends_on:
      - nats-account
      - nats
  nats-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: '-varz http://host.docker.internal:8222'
    ports:
      - 7777:7777
    depends_on:
      - nats
      - nats-account
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 8080:9090
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=qwerty
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
    prometheus_data:
    grafana_data:
networks: 
  default: 
      name: teta-external