version: "2.4"
services:
######## custom services with build
  keycloak:
    build:
      context: ../../keycloak
      dockerfile: ./Dockerfile
      args:
        KEYCLOAK_VERSION: 18.0.2
    image: keycloak:latest
    depends_on:
      - postgres
    environment:
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloakpass
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=db0
      - KC_DB=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=qazWSX123
    ports:
      - "8080:8080"
      - "8443:8443"
  postgres:
    build:
      context: ../../postgres
      dockerfile: ./Dockerfile
      args:
        POSTGRES_VERSION: 12.11
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres112
      - USER_NAME=keycloak
      - USER_PASSWORD=keycloakpass
      - SCHEMA_NAME=keycloak
    restart: always
    volumes:
      - keycloak_postgres_demo:/var/lib/postgresql/data
volumes:
  keycloak_postgres_demo: null
networks: 
  default: 
      name: keycloak-demo

